"""Deterministic mock LLM for local testing — no API key required.

Responses are generated by simple template rules so that tests are
stable and completely offline.
"""
from __future__ import annotations

from typing import Dict, List


_DEFAULT_RESPONSE = "[MockLLM] Acknowledged: {prompt}"


class MockLLM:
    """Drop-in mock for a language model.

    Parameters
    ----------
    responses:
        Optional mapping of *exact* prompt strings to canned responses.
        If the prompt is not in the map, a default template is used.
    """

    def __init__(self, responses: Dict[str, str] | None = None) -> None:
        self._responses: Dict[str, str] = responses or {}

    def chat(self, prompt: str) -> str:
        """Return a deterministic response for *prompt*."""
        if prompt in self._responses:
            return self._responses[prompt]
        return _DEFAULT_RESPONSE.format(prompt=prompt)

    def batch(self, prompts: List[str]) -> List[str]:
        """Return responses for a list of prompts."""
        return [self.chat(p) for p in prompts]
